### ISSUE TITLE
Unit Tests will always fail because 'ask_role' is defaulted to 'False'

### ISSUE THREAD

**Issue by paulieborg** [cevoaustralia/aws-google-auth#100]
I am trying to get UnitTests to work:

`python -m unittest discover . "test*.py"`

I get **4 failures** and they all seem to be for the same underlying reason.

Am I right that this clever coalesce function [# Ask Role (Option priority = ARGS, ENV_VAR, DEFAULT)](https://github.com/cevoaustralia/aws-google-auth/blob/91cb4f764655082631b61d8c1ba07742dbe9f6f0/aws_google_auth/__init__.py#L92)
```
        config.ask_role = bool(coalesce(
        args.ask_role,
        os.getenv('AWS_ASK_ROLE'),
        config.ask_role))
```

Will always return 'False' as the value in `args.ask_role` is not `None` it is set to `False` by  Default in `configuration.py`
_In [Class Configuration](https://github.com/cevoaustralia/aws-google-auth/blob/91cb4f764655082631b61d8c1ba07742dbe9f6f0/aws_google_auth/configuration.py#L21)_

```
        # Set up some defaults. These can be overridden as fit.
        self.ask_role = False
        ...
        ...
```
In this case, the value can never be overridden by environment??

(This also maybe flags the importance of Unit Tests in Travis Build ....)
Happy to be shot down!

**Comment by paulieborg** [comment]
I'll withdraw this. The unittests can be run using the `nosetests` module
The decorator `@nottest` is skipping this.

**Comment by stevemac007** [comment]
This is a good point @paulieborg - These tests were written as part of some earlier work and I noticed exactly what your opening comments mentioned.

I left these tests in so that this discussion could review if there is a better way to structure the codebase so these are not invalid.
