### ISSUE TITLE
Remember the device when aws-google-auth was used

### ISSUE THREAD

**Issue by f-barth** [cevoaustralia/aws-google-auth#107]
When using this wonderful piece of tech to authenticate I get warnings from Google on a regular base:
* "New device just logged in!"
* "Was that you?"
* etc

Is this a known problem? Is there a way to store some kind of token / identifier / etc that allows google to remember that this device did already authenticate?

**Comment by stevemac007** [comment]
If anyone can work out why this is triggered I'd be happy to implement the fix.

I've spent a few nights reviewing and parsing the HTML of the pages to try and stop this, but no luck finding the combination.  My guess is that some cookies or settings are not tracked properly.

It's annoying, but doesn't seem to impact the function of the tool.

**Comment by mide** [comment]
I personally haven't seen this problem - unless I'm actually on a new device (or on a new network). I do not normally see an email each time I auth into `aws-google-auth`. 

_(But that's just me - I'm not proposing this isn't an issue)_

**Comment by stevemac007** [comment]
I've actually found if you follow the link and click through to confirm this is valid that it stops these emails for a while.
