### ISSUE TITLE
Docker container won't show CAPTCHA image or url

### ISSUE THREAD

**Issue by fenak** [cevoaustralia/aws-google-auth#111]
Related comment: https://github.com/cevoaustralia/aws-google-auth/pull/91#issuecomment-413438202

When running this library on docker, opening the CAPTCHA image won't work, but won't raise an exception, prompting the user to enter the CAPTCHA with no option available to actually see it.

There are a few PRs open for this issue (https://github.com/cevoaustralia/aws-google-auth/pull/109 and https://github.com/cevoaustralia/aws-google-auth/pull/105) that attempt to fix it, and although I think it shouldn't try to open the image if the tools are not available (#105), I think the CAPTCHA url should be shown every time anyway.

When running from my Mac I accidentally closed the image window, and had to restart the process again, as I could not revisit the CAPTCHA. I'll be sending a PR with the solution I'm using.

**Comment by stevemac007** [comment]
I believe this is fixed with `0.0.28` - please verify and re-open if you continue to have issues.
