### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by suved-adkar-da** [cevoaustralia/aws-google-auth#115]
The Captcha can be difficult to read. Is there any way to disable the use of Captcha?

**Comment by stevemac007** [comment]
I wish this is something we can control, but the captcha is part of the Google authentication workflow.

It seems that using this tool causes Google to turn on extra validation for a while, in most cases the captcha seems to disappear again after a few days.

We've done some of the heavy lifting by downloading and displaying the image for you - I know it can be hard to read at times and is annoying - from personal experience, in a few days the captcha disappeared and I went back to being able to just 2FA on my device to auth through.
