### ISSUE TITLE
Error in case of extra comma

### ISSUE THREAD

**Issue by pioneerit** [cevoaustralia/aws-google-auth#12]
Hi and thanks for good tool. It is much better than my custom script.
I had an error today:
```Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.8', 'console_scripts', 'aws-google-auth')()
  File "/Library/Python/2.7/site-packages/aws_google_auth/__init__.py", line 327, in cli
    roles = dict([x.split(',') for x in doc.xpath('//*[@Name = "https://aws.amazon.com/SAML/Attributes/Role"]//text()')])
ValueError: dictionary update sequence element #0 has length 3; 2 is required
```

So the problem that I had configured:
`<role-arn>,<idp-arn>,` - for all my roles. And this is a valid description for the AWS. All login operations working fine.

**Solution:**
In my cases, I updated the Google Attributes for the user - removed the second comma.
I don't know if it is needed somehow checked in this tool, perhaps someone will find the error and apply the same solution.

**Comment by nonspecialist** [comment]
Should be fixed by PR #16 (fix available in 0.0.10)
