### ISSUE TITLE
Suppress output

### ISSUE THREAD

**Issue by johnplaydrums** [cevoaustralia/aws-google-auth#123]
Hello! Just started integrating this tool into our stack and I LOVE it. So first off, thank you! I'm wondering if it's possible to suppress some of the output from `aws-google-auth`. For instance the `Assuming arn:aws:iam...` and `Credentials Expiration` output. We wrap this tool in our own CLI and like to be able to control exactly what output the user sees (so we can standardize across all our commands). Is this possible? I can't suppress all output because I still need the prompts. If this is something you'd like to integrate I can try to find time to PR it.

**Comment by stevemac007** [comment]
Contributions are always welcome and I can see how having an option to suppress the output would be useful for your case.

Maybe adding something like a `-q` option for `--quiet` to remove any additional output for streamlined use.

**Comment by johnplaydrums** [comment]
Sounds good! I will try to carve out some time asap. Thanks

**Comment by johnplaydrums** [comment]
Alright I have a commit with a first pass at a quiet option. Do I need some permissions to push my branch up? I tried `git push origin add-quiet-option` but got a 403 from github. Thanks!

**Comment by stevemac007** [comment]
Fork the repo and push your branch to the fork - you can then create a Pull Request from your fork to our repo, where we can review and accept.

thanks for taking the time to develop the enhancements, looking forward to 👀 it...

**Comment by johnplaydrums** [comment]
Thanks i'm an open source noob. here's the pr! https://github.com/cevoaustralia/aws-google-auth/pull/124

**Comment by stevemac007** [comment]
We all were once :D

**Comment by stevemac007** [comment]
Released with https://pypi.org/project/aws-google-auth/0.0.30/
