### ISSUE TITLE
I get prompted to "Open the Google App" but I have this factor disabled

### ISSUE THREAD

**Issue by max-rocket-internet** [cevoaustralia/aws-google-auth#146]
I have Google prompt on my phone turned in my Google account but when I run `aws-google-auth` it always shows: `Open the Google App, and tap 'Yes' on the prompt to sign in ...`.

I have to `ctrl-c` about 4-6 times and then it shows the `Choose MFA method from available:` prompt where I can choose TOTP.

Anyone else have this issue? Is it a Google problem?

**Comment by stevemac007** [comment]
Are you still getting this @max-rocket-internet ?

**Comment by max-rocket-internet** [comment]
No. Well, it went away. Then came back again, then went away.

I don't know 🙂
