### ISSUE TITLE
Android security key causes error

### ISSUE THREAD

**Issue by ljbade** [cevoaustralia/aws-google-auth#154]
I get an error if I have an Android device selected as the security key in Google. See screenshot below (ignore the USB key, if I remove the USB key then I get the error as it tries the phone first):

![image](https://user-images.githubusercontent.com/1215089/68282202-56a26380-00cd-11ea-9027-f20a2915ce33.png)

```
ERROR:root:Was unable to find appid value in googles SAML page
Traceback (most recent call last):
  File "/home/leith/.local/lib/python3.6/site-packages/aws_google_auth/google.py", line 165, in find_app_id
    searchResult = re.search('"appid":"[a-z://.-_]+"', inputString).group()
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by stevemac007** [comment]
Latest release 0.0.33 I believe fixes this issue with the #145 fix.
Please let me know if this still happens.

**Comment by ljbade** [comment]
@stevemac007 yes this release no longer crashes when I enable both keys.

Unfortunately it looks like I need to wait for a new release of https://github.com/Yubico/python-u2flib-host before my Thetis U2F key works on Linux. Hopefully it doesn't take too long.

**Comment by stevemac007** [comment]
Hopefull - thanks for confirming @ljbade
