### ISSUE TITLE
Default region of ap-southeast-2 selected

### ISSUE THREAD

**Issue by pmarkert** [cevoaustralia/aws-google-auth#156]
When initializing a new profile and answering the prompts, the saved ~/.aws/config defaults to the region ap-southeast-2. Is this intentional? Perhaps it should prompt the user to select a region or alternatively not add a region to the config section.

**Comment by stevemac007** [comment]
Yes - you are right, it does default there - most probably due to me being in Australia and that being my default region.

This can be controlled by the command line:
```
 -R REGION, --region REGION
                        AWS region endpoint ($AWS_DEFAULT_REGION)
```

Enhancement request appreciated to make this more interactive if a value is not supplied using these methods.

**Comment by stevemac007** [comment]
Will be part of the next release.
