### ISSUE TITLE
Google Prompt timeout after successive logins

### ISSUE THREAD

**Issue by amanbrarlime** [cevoaustralia/aws-google-auth#171]
When I run this command multiple times in quick succession with different profile names to create multiple profiles, I hit this error very often: 

`Something went wrong - Could not find SAML response, check your credentials or use --save-failure-html to debug.`

The first run is always fine, but successive runs after that fail majority of the time

It produces this html:

![image](https://user-images.githubusercontent.com/59583978/75577791-96dc7780-5a17-11ea-8be6-30374159b624.png)

This issue appears to be specific to Google Prompt MFA, it seems to work fine for me when I use SMS messages as MFA instead

It looks like it might be related to this issue: https://github.com/cevoaustralia/aws-google-auth/issues/138

**Comment by stevemac007** [comment]
This is usually something to do with the state of your account - work in progress with `cookie` storing and `page-debug` might help track this down.  Please re-open if this continues to happen.
