### ISSUE TITLE
Invalid username or password

### ISSUE THREAD

**Issue by h6ah4i** [cevoaustralia/aws-google-auth#192]
I am facing the `Invalid username or password` error since today. I guess Google has made changes to the login screen recently. 

```bash
$ aws-google-auth --profile foobar
Google Password:
Invalid username or password

$ aws-google-auth --version
aws-google-auth 0.0.34
```

**Comment by bryancalvobenoit** [comment]
I am facing the same issue. 
```
$ aws-google-auth --version
aws-google-auth 0.0.34
```

**Comment by JPLemelin** [comment]
Same here
```
$ aws-google-auth --version
aws-google-auth 0.0.35
```

**Comment by Wingjam** [comment]
Update your `aws-google-auth` version to 0.0.36, there is now a captcha validation!

**Comment by JPLemelin** [comment]
It's work with 0.0.36

**Comment by bryancalvobenoit** [comment]
It worked with 0.0.36 for me thanks @Wingjam

**Comment by h6ah4i** [comment]
@Wingjam Thank you for the quick response! I've also confirmed that v0.0.36 worked for me 👍
