### ISSUE TITLE
How to switch role?

### ISSUE THREAD

**Issue by kirankraleti** [cevoaustralia/aws-google-auth#193]
I have an AWS account from which I would switch to multiple other AWS accounts.

I'm able to fetch credentials to the 1st AWS account. I would like to understand how I can switch my role into other accounts using aws-google-auth

**Comment by Akin2Silver** [comment]
aws-google-auth will simply pull in the details of what accounts are available to your user. 
To have more accounts show in the app you just need to add them at the google level.
