### ISSUE TITLE
Lots of new CAPTCHAs

### ISSUE THREAD

**Issue by Nuru** [cevoaustralia/aws-google-auth#197]
I went months without getting a CAPTCHA but since around the beginning of September I am getting them every day. Is it just me? Did something change in the login page that `aws-google-auth` is not handling and is making Google suspicious?

**Comment by Akin2Silver** [comment]
Yeah, I have been getting the same with almost every authentication request. 

Auth still works so nothing is broken. Would just be nice to not trigger the capture if possible.

**Comment by eugenekainara** [comment]
I'm also expect following issue with CAPTCHA prompt on every login but it starts on the beginning of October.

**Comment by danhopkins** [comment]
Same here. They seem to come in flurries: every day for a week or so, then not for a few days. Incredibly annoying if you usually pipe a password in from a password manager.

**Comment by scottharrisaus** [comment]
I downgraded from python 3.8.5 to 3.8.2 and fixed issue,  was happening every day on 3.8.5.

Not sure yet what the change is from 3.8.2 that breaks it

**Comment by scottharrisaus** [comment]
sorry not directly related to version,  when i downgraded i used asdf to install python 3.8.2 .  urllib3 using asdf version of python was using version 1.26.2  when getting captchas it was on version 1.25.8

**Comment by eugenekainara** [comment]
Upgrade to python 3.9(from 3.8) solve issue for me on Mac OS

**Comment by ostmike** [comment]
> Upgrade to python 3.9(from 3.8) solve issue for me on Mac OS
Doesn't seem to have made any difference to me on Ubuntu 20.04

> sorry not directly related to version, when i downgraded i used asdf to install python 3.8.2 . urllib3 using asdf version of python was using version 1.26.2 when getting captchas it was on version 1.25.8
upgrading urllib3 to 1.26.2 did the trick for me. awscli/boto3/botocore needed upgrading to allow me to do so, that' all good though. I do now get a warning when I run aws-google-auth:
```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
```
no more CAPTCHAs though :+1:

**Comment by danhopkins** [comment]
> upgrading urllib3 to 1.26.2 did the trick for me. awscli/boto3/botocore needed upgrading to allow me to do so, that' all good though. I do now get a warning when I run aws-google-auth:
> 
> ```
> /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
>   warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
> ```
> 
> no more CAPTCHAs though

I got similar (on OSX) when upgrading `urllib3` alone. brew upgrading Python (3.8.6) then `requests` (2.25.0, which downgraded urllib back to 1.25.11, then manually upgrading `urllib` again took it back to 1.26.2, with no more supported version warnings from `requests`) YMMV :)

**Comment by cippaciong** [comment]
For those who installed `aws-google-auth` using Homebrew, I submitted a PR to upgrade the `urllib3` and `requests` dependencies and it's already merged.

If you upgrade your package your should stop seeing the CAPTCHAs problem 🙂.

**Comment by stevemac007** [comment]
Thanks for the Homebrew update - plz let us know if this does not resolve the issue.
