### ISSUE TITLE
Feature Request: Support for Google Prompt push notification

### ISSUE THREAD

**Issue by TJatAgari** [cevoaustralia/aws-google-auth#2]
When Google Prompt enabled for 2-Step verification the following error is generated. It would be really nice to have support for Google Prompt.
----

`$ aws-google-auth 
Setting duration to 3600 seconds
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 9, in <module>
    load_entry_point('aws-google-auth==0.0.5', 'console_scripts', 'aws-google-auth')()
  File "/Library/Python/2.7/site-packages/aws_google_auth/__init__.py", line 229, in cli
    google.do_login()
  File "/Library/Python/2.7/site-packages/aws_google_auth/__init__.py", line 140, in do_login
    challenge_id = challenge_url.split("totp/")[1]
IndexError: list index out of range
`

**Comment by nonspecialist** [comment]
I'd be happy to add it -- I haven't used Google Prompt before, but I'll see how I go about enabling it and work out where to go from there.

Thanks for the feature request!

**Comment by nonspecialist** [comment]
Google Prompt support added. I only have a single device I can test it on (iPhone), so more feedback would be welcome to confirm whether this issue can be closed
