### ISSUE TITLE
Suppress google security alerts

### ISSUE THREAD

**Issue by afosterw** [cevoaustralia/aws-google-auth#21]
Awesome tool!

I'm working on a patch to add a cookie store to suppress the Security alerts generated every time I use the script. Let me know if you have any other ideas or concerns regarding this issue.

**Comment by afosterw** [comment]
My fork is here:
https://github.com/lovepopcards/aws-google-auth

**Comment by nonspecialist** [comment]
Thanks @afosterw -- pull requests are welcome. Could you include some examples of the security alerts in this issue so others who are suffering the same problem could find it more easily?

Also, it would help to know:
* what platform you're using (eg Windows/OSX/Linux, which OS version/distro)
* whether you're using the bare Python version or the Docker version
* command-line flags which trigger/do not trigger the alerts

**Comment by afosterw** [comment]
It looks like this was happening on the google side. As soon as I accepted the alerts from google web UI (instead of the android notification) they went away. Closing.
