### ISSUE TITLE
Release 0.0.37 missing on PyPI

### ISSUE THREAD

**Issue by uguy** [cevoaustralia/aws-google-auth#215]
Hi guys, the latest release (0.0.37) is missing on PyPI.org.

Is this something normal from your release process or maybe there was some kind of failure during the publishing ?

https://pypi.org/project/aws-google-auth/#history

Looks like there was a problem when publishing ?

(at the end - failed to deploy)
https://travis-ci.org/github/cevoaustralia/aws-google-auth/jobs/756567473

```
Installing deploy dependencies
Successfully installed dpl-pypi-1.10.16
Parsing documentation for dpl-pypi-1.10.16
Installing ri documentation for dpl-pypi-1.10.16
Done installing documentation for dpl-pypi after 0 seconds
1 gem installed
2021-01-29 01:27:05 URL:https://bootstrap.pypa.io/get-pip.py [1928477/1928477] -> "-" [1]
Traceback (most recent call last):
  File "<stdin>", line 24226, in <module>
  File "<stdin>", line 199, in main
  File "<stdin>", line 82, in bootstrap
  File "/tmp/tmpRNT5GI/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
Couldn't install pip, setuptools, twine or wheel.
failed to deploy
```

**Comment by stevemac007** [comment]
Usually deploys push out through travis CI - but the jobs were queued for hours and then cancelled.

I'm moving over to GitHub actions to deploy - just need a couple of clean hours to get it working (things are busy at work today).

**Comment by stevemac007** [comment]
Found my issue - the updated build should now be on pypi.
