### ISSUE TITLE
New prompt? Could not find SAML response

### ISSUE THREAD

**Issue by p-doyle** [cevoaustralia/aws-google-auth#221]
When running command:
`aws-google-auth -u me@company.com -I abc123 -S 1234 -d 28800 -p default --region us-east-1 --save-failure-html`

The error is:
`Something went wrong - Could not find SAML response, check your credentials or use --save-failure-html to debug`

I do receive a prompt on my phone for the 2FA, though it looks a little different than what I remember, and it was working fine a few days ago.  The failure html page looks like this:
![Screenshot_339](https://user-images.githubusercontent.com/16737327/107822110-2e2efd80-6d43-11eb-8d07-09fb3ec9a24c.png)

Is this a new prompt or could there be something else going on?

**Comment by funollet** [comment]
Upgrading to 0.0.37 seems to solve this specific issue. Did you tried this version?

**Comment by p-doyle** [comment]
I am on 0.0.37.  Using Windows 10 64bit with Python 3.7.4.

**Comment by JamesMarino** [comment]
Can confirm version `0.0.37` has solved this issue for me using the `cevoaustralia/aws-google-auth:0.0.37` Docker image

**Comment by p-doyle** [comment]
Looks like there was either a conflict with another python installation or I had upgraded the package without admin... resolved now.  Thanks!
