### ISSUE TITLE
 'NoneType' object has no attribute 'get' 'https://accounts.google.com' + form.get('action') - Not Able to Login 

### ISSUE THREAD

**Issue by Renjie-d1g1t** [cevoaustralia/aws-google-auth#252]
Is there any solution, how to resolve this it?
The same issue:

aws-google-auth -I ******* -S xxxxxxx -d 28800 -p lmg -R ****** [-uuser@email.com](mailto:-uuser@email.com) -k -l debug

```
INFO:root:aws_google_auth: SAML cache not found
DEBUG:keyring.backend:Loading Gnome
DEBUG:keyring.backend:Loading Google
DEBUG:keyring.backend:Loading Windows (alt)
DEBUG:keyring.backend:Loading file
DEBUG:keyring.backend:Loading keyczar
DEBUG:keyring.backend:Loading multi
DEBUG:keyring.backend:Loading pyfs
DEBUG:keyring.backend:Loading KWallet
DEBUG:keyring.backend:Loading SecretService
DEBUG:keyring.backend:Loading Windows
DEBUG:keyring.backend:Loading chainer
DEBUG:keyring.backend:Loading libsecret
DEBUG:keyring.backend:Loading macOS
Google Password:
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): accounts.google.com:443
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /o/saml2/initsso?idpid=Cxxxxxxx&spid=9xxxxxxxxx&forceauthn=false HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /ServiceLogin?passive=1xxxxxx&continue=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxx%26spid%3xxxxxxxxxx%26forceauthn%3Dfalse%26from_login%3Dxxxxxxxxxxxxxxxxxx&followup=https://accounts.google.com/o/saml2/initsso?idpid%3xxxxxxxxxxxxxforceauthn%3Dfalse%26from_login%3xxxxxxxxxxxxxxxxxxxxx=popup&oauth=1&faa=1&sarp=1&scc=1 HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "POST /signin/v1/lookup HTTP/1.1" 302 242
DEBUG:urllib3.connectionpool:https://accounts.google.com:443 "GET /signin/rejected?rrk=88&hl=ru HTTP/1.1" 200 None
INFO:root:Handling new-style login page
ERROR:root:'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 79, in cli
    process_auth(args, config)
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 243, in process_auth
    google_client.do_login()
  File "/usr/local/lib/python3.6/site-packages/aws_google_auth/google.py", line 256, in do_login
    passwd_challenge_url = 'https://accounts.google.com' + form.get('action')
AttributeError: 'NoneType' object has no attribute 'get'
```

I`ve tried with deferent OS:

CentOS v8; Python 3.6.8; pip 21.3.1; aws-google-auth 0.0.37; aws-cli/2.5.4
"Debian GNU/Linux 11; Python 3.9.2; pip 22.0.4; aws-google-auth 0.0.37; aws-cli/2.5.4
The same result 1:1

_Originally posted by @myl82 in https://github.com/cevoaustralia/aws-google-auth/issues/164#issuecomment-1097661518_

**Comment by deegital** [comment]
Same issue as in https://github.com/cevoaustralia/aws-google-auth/issues/248, you'll find a fix there :)

**Comment by juan-vg** [comment]
Fix: https://github.com/cevoaustralia/aws-google-auth/pull/251

**Comment by Renjie-d1g1t** [comment]
> Same issue as in #248, you'll find a fix there :)

Thanks for sharing! I got to the captcha after I added both --bg-response and  js_enabled, however it is still giving me errors luke beliow :

 -k -p default --bg-response js_enabled
Google Password:
Please visit the following URL to view your CAPTCHA: https://accounts.google.com/Captcha?v=2&ctoken=AAWk9lSXXahGTVie5CcbJlEpHwsscQjYaV4eFjsABMY_PV8PuYopQgzxhxfDOBj98yyP6wQqCAlA8l3VzTt_uTQL7K8MrDcK-Kgx1GYzxHsKyllTJak57rP7kiADvsAkRWrVRkaf0__DygWyieK7TobPkjKiiDdyhAd3Tc5eU5Z9Q9N5KATiBH4
Captcha (case insensitive): ducarnshes
ERROR:root:'NoneType' object has no attribute 'find_all'
Traceback (most recent call last):
  File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\__init__.py", line 79, in cli
    process_auth(args, config)
  File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\__init__.py", line 243, in process_auth
    google_client.do_login()
  File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\google.py", line 291, in do_login
    sess = self.handle_captcha(sess, payload)
  File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\google.py", line 432, in handle_captcha
    for tag in form.find_all('input'):
AttributeError: 'NoneType' object has no attribute 'find_all'

**Comment by Renjie-d1g1t** [comment]
> > Same issue as in #248, you'll find a fix there :)
> 
> Thanks for sharing! I got to the captcha after I added both --bg-response and js_enabled, however it is still giving me errors luke beliow :
> 
> -k -p default --bg-response js_enabled Google Password: Please visit the following URL to view your CAPTCHA: https://accounts.google.com/Captcha?v=2&ctoken=AAWk9lSXXahGTVie5CcbJlEpHwsscQjYaV4eFjsABMY_PV8PuYopQgzxhxfDOBj98yyP6wQqCAlA8l3VzTt_uTQL7K8MrDcK-Kgx1GYzxHsKyllTJak57rP7kiADvsAkRWrVRkaf0__DygWyieK7TobPkjKiiDdyhAd3Tc5eU5Z9Q9N5KATiBH4 Captcha (case insensitive): ducarnshes ERROR:root:'NoneType' object has no attribute 'find_all' Traceback (most recent call last): File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth__init__.py", line 79, in cli process_auth(args, config) File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth__init__.py", line 243, in process_auth google_client.do_login() File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\google.py", line 291, in do_login sess = self.handle_captcha(sess, payload) File "C:\Users\Renjie Li\Downloads\Anaconda\lib\site-packages\aws_google_auth\google.py", line 432, in handle_captcha for tag in form.find_all('input'): AttributeError: 'NoneType' object has no attribute 'find_all'






I think it is about google account setting because I just tried to use someone else's login it worked

so nothing to do with environment, guess just the way we set up google account

my account : ask for password - captcha - error
another account: ask for password - captcha - ask for authenticator code

**Comment by wbrgss** [comment]
@Renjie-d1g1t I recommend patching your local installation with[ezequielbarros](https://github.com/ezequielbarros)'s change as per https://github.com/cevoaustralia/aws-google-auth/issues/248#issuecomment-1102707053
