### ISSUE TITLE
'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by stevemac007** [cevoaustralia/aws-google-auth#3]
I'm using version 0.0.5 of the library and have set configuration via environment variables but having issues.

```
$ export GOOGLE_IDP_ID=<google_idp_id>
$ export GOOGLE_SP_ID=<google_sp_id>
$ export GOOGLE_USERNAME=<my_email_address>
```

When running `aws-google-auth` I get the following issue.

```
Password: 
Traceback (most recent call last):
  File "/usr/local/bin/aws-google-auth", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 229, in cli
    google.do_login()
  File "/usr/local/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 137, in do_login
    tl = response_page.find('input', {'name': 'TL'}).get('value')
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by stevemac007** [comment]
From troubleshooting it seems that it is falsely identifying that I am using an MFA.  (In this case I am not).

When I change:
```
        if sess.url.find("totp/"):
```

to

```
        if False and sess.url.find("totp/"):
```

(ie. disable the MFA detection) My login is successful.

The `sess_url` in this case is `https://accounts.google.com/o/saml2/initsso?idpid=IDP&spid=SP&forceauthn=false&from_login=1&as=AS&authuser=0`

Given there is no `totp/` in the string I guess the issue is with the `find`.
I assume this is trying to do a string contains search, and might be better to use.

```
        if "totp/" in sess.url:
```

I don't have an MFA enabled account to confirm this is valid.

**Comment by nonspecialist** [comment]
Closing as complete

**Comment by zglozman** [comment]
I am getting this issue with  0.0.25, why ?
