### ISSUE TITLE
Feature: assume cross account role

### ISSUE THREAD

**Issue by voukka** [cevoaustralia/aws-google-auth#42]
Congrats! This is a useful tool 👍  

Though we could improve it for cross-account AWS setup. 

Some might find it easier to manage federated SSO if it is mapped to few roles of `Accounts` AWS account (`X` on diagram). Other AWS accounts roles are mapped to the `Accounts'` roles, eg: `Dev` roles on `Staging` and `Production` accounts are have cross-account trust to `Dev` role on `X`, etc. That way only few values needs to be pushed to google user profiles and it scales if number of AWS accounts increases.

Diagram:
```
# Currently supported multirole through custom musti-value profile field:
# --role-arn A
               -> { Option A   -> AWS Acc X, Role A
Google SSO App -> { Option B   -> AWS Acc X, Role B
               -> { Option C   -> AWS Acc X, Role C
                  
#Proposed for cross account setup
# --role-arn Dev --xa-role-arn Z-Dev [--xa-role-profile]
                                                            -> { Acc Y, Role Dev
Google SSO App -> { Option Dev   -> AWS Acc X, Role Dev     -> { Acc Z, Role Dev

                                                            -> { Acc Y, Role Admin
               -> { Option Admin -> AWS Acc X, Role Admin   -> { Acc Z, Role Admin
```

With current state of the tool to assume cross-account role for CLI requires something like:
```bash
aws-google-auth -a --sp-id 123456 --idp-id C01example --username user@example.com

aws sts assume-role --role-arn "arn:aws:iam::123455678:role/Dev" --profile sts

# here you need to parse output of the prev command and, for example, export it to env:

export AWS_ACCESS_KEY_ID=XKLKJLDFLDKLF
export AWS_SECRET_ACCESS_KEY="EXAMPLESECRET"
export AWS_SESSION_TOKEN="TOKENFOO"
```

It be nice to add feature to assume sts credentials for `--xa-role-arn` option and write down profile to config `--xa-role-profile`.

**Comment by SamBarker** [comment]
While I think cross organisation handling could be improved we've managed things by setting up
~/.aws/config something like:

```
[profile mgmt]
role_arn = arn:aws:iam::123455678:role/Dev
source_profile = PROD-RO

[profile PROD-RO]
region = ap-southeast-2
...
```

Where PROD-RO is generated by aws-google-auth

**Comment by voukka** [comment]
Thanks Sam for clarification! 

Somehow I missed that once there are aws credentials for `gateway` account, it is possible to use documented config for [cross account roles](https://docs.aws.amazon.com/cli/latest/userguide/cli-roles.html#cli-roles-xaccount). I close this ticket.
