### ISSUE TITLE
RuntimeError: Could not find SAML response, check your credentials

### ISSUE THREAD

**Issue by JeremJR** [cevoaustralia/aws-google-auth#60]
While using aws-google-auth from ec2 instances with various ip I've encountered some cases not yet handled :

```
aws-google-auth --idp-id C01234567 --sp-id 123456789012 -u xxxx.xxxx@example.com -p default
Google Password: 
Traceback (most recent call last):
  File "/usr/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth==0.0.20', 'console_scripts', 'aws-google-auth')()
  File "/usr/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 54, in main
    cli(sys.argv[1:])
  File "/usr/lib/python2.7/site-packages/aws_google_auth/__init__.py", line 160, in cli
    saml_xml = google_client.parse_saml()
  File "/usr/lib/python2.7/site-packages/aws_google_auth/google.py", line 153, in parse_saml
    raise RuntimeError('Could not find SAML response, check your credentials')
RuntimeError: Could not find SAML response, check your credentials
```

For some user I may have to select the challenge https://raw.githubusercontent.com/JeremJR/aws-google-auth/issue/aws_google_auth/tests/selectchallenge_2.html
For another user I may have to enter a phone number to retrieve a token https://raw.githubusercontent.com/JeremJR/aws-google-auth/issue/aws_google_auth/tests/challenge_iap_3.html

I have proposed a PR to handle such cases : https://github.com/cevoaustralia/aws-google-auth/pull/54
But I have no feeback on it yet, maybe due to the coverage test issue.
If so, any advices will be appreciated in order to help increasing the test coverage.

**Comment by stevemac007** [comment]
Resolved with merge of #54 - please reopen if the issue persists.
