### ISSUE TITLE
Max duration for a session can be increased to 12h

### ISSUE THREAD

**Issue by dalen** [cevoaustralia/aws-google-auth#66]
The limit was recently increased on the AWS side: https://aws.amazon.com/about-aws/whats-new/2018/03/longer-role-sessions/

**Comment by nonspecialist** [comment]
Yes! This is going to be _so much nicer_

**Comment by dalen** [comment]
Created a PR for it as well :) https://github.com/cevoaustralia/aws-google-auth/pull/67

**Comment by nonspecialist** [comment]
Thanks!
