### ISSUE TITLE
Google Prompt 2FA broken. "raise ValueError(response)" in google.py check_extra_step()

### ISSUE THREAD

**Issue by FrederikNS** [cevoaustralia/aws-google-auth#68]
I just tested out 0.0.23 and 0.0.22, but I receive an error when I get to the 2-factor step.

First the CLI asks me for my google password, then it responds with an error:

    Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.
    Google Password:
    This extra step shows that it’s really you trying to sign in
    Traceback (most recent call last):
      File "/usr/local/bin/aws-google-auth", line 11, in <module>
        load_entry_point('aws-google-auth==0.0.22', 'console_scripts', 'aws-google-auth')()
      File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 54, in main
        cli(sys.argv[1:])
      File "/usr/local/lib/python3.6/site-packages/aws_google_auth/__init__.py", line 159, in cli
        google_client.do_login()
      File "/usr/local/lib/python3.6/site-packages/aws_google_auth/google.py", line 127, in do_login
        self.check_extra_step(response_page)
      File "/usr/local/lib/python3.6/site-packages/aws_google_auth/google.py", line 163, in check_extra_step
        raise ValueError(response)
    ValueError: {Some HTML}

I tried dumping the html to a file and opening it, which resulted in this:

![image](https://user-images.githubusercontent.com/181295/38236682-3faa602e-3725-11e8-9e0d-9285a156277d.png)

So it seems that 0.0.22 has broken the "Google Prompt" 2-factor challenge. I have not tested other 2FA methods.

I tested out 0.0.22, which shows the same issue. 0.0.21 does not suffer from the same problem though.

**Comment by stevemac007** [comment]
Doh! I'll have a look at the cause of this later tonight unless someone gets to it before me.

**Comment by stevemac007** [comment]
My account with token based 2FA works as expected, I'll have to setup a GooglePrompt version somehow to test the other modes.  My guess is this is part of changes to fix #52.

If you have some sample HTML you can attach, I'll put together some workflow to cover this scenario.
