### ISSUE TITLE
Question:  does your project use open APIs or some "hack"?

### ISSUE THREAD

**Issue by Hervian** [cevoaustralia/aws-google-auth#69]
Hi, this project looks great.

I have a question I hope you have the time to answer:
Does this project use some public Google APIs or does it use some kind of "hack"?

I don't have much knowledge about SAML and SSO, which my question my reflect. But I can see that Okta has a command line tool which allows to easily acquire temporary credentials for federated users and update the .aws/credentials file. That project, as I understand it, calls an Okta API to acquire a SAML assertion which is then forwarded to an AWS API.

I have read that Google does not expose their API for this, for which reason one must do stuff like browser automation to log in the user. The reason why I ask is because I am looking for a relatively stable solution that allows for easily changing AWS credentials to shift between accounts. (And Okta's product is too expensive)

Before finding your project, I considered created a G Suite version of Okta's tool, but I dropped the project since I could not find any way to acquire a SAML assertion from G Suite. Now I have found your project which seems to have solved the problem I had.

**Comment by stevemac007** [comment]
There is no published API for the Google SAML login that I've seen, we've pieced this together from different users contributing examples of web responses for different scenarios.
