### ISSUE TITLE
main() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by mide** [cevoaustralia/aws-google-auth#70]
I'm getting the following error, introduced in 48d22e4d62bb6e216cd8932739ea0be4735e2588 (Determined by `git bisect`). I don't have the time to dig right now, but I will later.

```
$ aws-google-auth --help 
Traceback (most recent call last):
  File "/Users/mide/virtualenv/aws-google-auth-dev/bin/aws-google-auth", line 11, in <module>
    load_entry_point('aws-google-auth', 'console_scripts', 'aws-google-auth')()
TypeError: main() takes exactly 1 argument (0 given)
```

**Comment by stevemac007** [comment]
Another Doh, was focused on the tests and never ran the tool from the cli, have a fix I'll push shortly.
