### ISSUE TITLE
Where is the SP ID in GSuite?

### ISSUE THREAD

**Issue by npetrovic-riparian** [cevoaustralia/aws-google-auth#76]
The instructions in the readme mention theres a url with a number when going to Apps > SAML Apps > Settings for Amazon Web Services in GSuite/Google Apps. However, I'm not seeing any such URL. 

![screen shot 2018-05-08 at 10 11 49 pm](https://user-images.githubusercontent.com/35978065/39792103-11c9259c-530d-11e8-913e-f1ac1f23d019.png)

Any help on where I can get the SP ID?

**Comment by tnh** [comment]
Hi all,

I don't have admin in GSuite so perhaps there is another way to find this out. The only way I am aware if finding the Service Provider ID is dumpster diving the URLs from my Google account. 
<img width="1599" alt="screen shot 2018-03-21 at 5 35 15 pm" src="https://user-images.githubusercontent.com/716595/40391052-79a9486a-5e5a-11e8-9cfa-53e9fa20b0be.png">

<img width="1599" alt="screen shot 2018-03-21 at 5 35 15 pm" src="https://user-images.githubusercontent.com/716595/40391139-b009c98e-5e5a-11e8-957e-e4e74e017097.png">

**Comment by ErmisCat** [comment]
That works, thanks.

**Comment by stevemac007** [comment]
Thanks @tnh for the alternate lookup suggestion.
