### ISSUE TITLE
Unable to install aws-google-auth with U2F libraries

### ISSUE THREAD

**Issue by kaldebert** [cevoaustralia/aws-google-auth#85]
When executing the command line:
`sudo pip install aws-google-auth[u2f]`
I got this error:
`no matches found: aws-google-auth[u2f]`

Could you help me with this?

The commande line `sudo pip install aws-google-auth` works well. The tool is installed but I got the message `Failed to import U2F libraries, U2F login unavailable. Other methods can still continue.` when I try to run the tool.

**Comment by stevemac007** [comment]
I'm not actually sure how this works myself (not having a u2f device).

Let me investigate and see if we need updated instructions.

**Comment by ErmisCat** [comment]
Are you using ZSH? You can either try to escape the brackets or just use bash to install.

**Comment by kaldebert** [comment]
I'm using ZSH. You're right it was just an escaping issue.
It works with:
`pip install --user "aws-google-auth[u2f]"`

**Comment by stevemac007** [comment]
Great to know - Thanks @ErmisCat for the pointer - I'll add a note to the README to highlight this.
