### ISSUE TITLE
No credential exports printed when using docker.

### ISSUE THREAD

**Issue by jgissend10** [cevoaustralia/aws-google-auth#96]
The credential exports aren't printed when using docker. It seems the config.profile has a value no matter what and the else that should print them is never reached.

**Comment by wcharaka** [comment]
@jgissend10  I think you are right. It seems in `Configuration` the `self.profile` is defaults to sts hence 
```
if config.profile:
        config.write(amazon_client)
else:
        amazon_client.print_export_line()
```
will always be true so it would never be true. two options I can think of is either you can print it always. or you print based on a parameter. I find the latter more secure as I m not sure if we should just print the keys in the terminal. Thoughts..?

**Comment by jgissend10** [comment]
I'd prefer a parameter and to just replace the else with 'if parameter:'
that way I can print it out even if we're writing the config to the client.

**Comment by jgissend10** [comment]
Any update on this?

**Comment by stevemac007** [comment]
@wcharaka are you still looking at this one, otherwise I'm happy to pick this up and get it working agin.

**Comment by wcharaka** [comment]
@stevemac007 I m on it..

**Comment by wcharaka** [comment]
This has been fixed and released.
