### ISSUE TITLE
Forbidden accessing https://accounts.google.com/o/saml2/initsso?idpid=<redacted>&spid=<redacted>&forceauthn=false&from_login=1&as=<redacted>

### ISSUE THREAD

**Issue by sinkr** [cevoaustralia/aws-google-auth#98]
Hello, on version 0.0.27 (tested on 0.0.25, too).

This previously worked, however, I now get the "forbidden accessing" message above. 

Any suggestions where to look?

**Comment by sinkr** [comment]
User error.

**Comment by C-Kenny** [comment]
Hello from Google search results, I got this error by providing a mistype `SPID`.
